name: PR review by Claude

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Fetch target branch
        run: |
          git fetch --depth 1 origin ${{ github.event.pull_request.base.ref }}

      - name: PR Review with Custom Command
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          track_progress: true
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}
            BASE BRANCH: ${{ github.event.pull_request.base.ref }}
            HEAD BRANCH: ${{ github.event.pull_request.head.ref }}

            /review-code ${{ github.event.pull_request.base.sha }}

            Use inline comments for specific code issues and file-level problems.
            Use top-level PR comments for general observations, summary, and overall recommendations.

          # Tools for comprehensive PR review
          claude_args: |
            --allowedTools "mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(git diff:*)"