name: 'Verify frontend build'

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Verify frontend build
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    defaults:
      run:
        working-directory: './frontend'
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: './frontend/.nvmrc'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Verify linting
        run: npm run lint:check
        continue-on-error: false

      - name: Verify formatting
        run: npm run format:check
        continue-on-error: false

      - name: Test types
        run: npm run test:ts
        continue-on-error: false

      - name: Build
        run: npm run build
        continue-on-error: false