name: 'Build and test API'

on:
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: '9.x'

jobs:
  build-and-test:
    name: Build and test API
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: './api'

    steps:
      - uses: actions/checkout@v4

      - name: Set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal